import { pgTable, text, integer, boolean, timestamp, numeric, jsonb } from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  passwordHash: text('password_hash'),
  googleId: text('google_id').unique(),
  profilePicture: text('profile_picture'),
  role: text('role').default('customer').notNull(),
  status: text('status').default('approved').notNull(),
  isPasswordResetRequired: boolean('is_password_reset_required').default(false),
  phone: text('phone'),
  pharmacyName: text('pharmacy_name'),
  address: jsonb('address'),
  otp: text('otp'),
  otpExpiresAt: timestamp('otp_expires_at'),
  bankDetails: jsonb('bank_details'),
  pharmacyCertificate: text('pharmacy_certificate'),
  location: jsonb('location'),
  kycStatus: text('kyc_status').default('Pending'),
  aadhaarNumber: text('aadhaar_number'),
  aadhaarCardUrl: text('aadhaar_card_url'),
  ownerPhotoUrl: text('owner_photo_url'),
  ownerPan: text('owner_pan'),
  panCardUrl: text('pan_card_url'),
  businessPan: text('business_pan'),
  businessType: text('business_type'),
  yearsInOperation: integer('years_in_operation'),
  retailDrugLicense: text('retail_drug_license'),
  drugLicenseNumber: text('drug_license_number'),
  licenseExpiryDate: timestamp('license_expiry_date'),
  pharmacistCertificate: text('pharmacist_certificate'),
  gstNumber: text('gst_number'),
  cancelledChequeUrl: text('cancelled_cheque_url'),
  shopEstablishmentUrl: text('shop_establishment_url'),
  rentAgreementUrl: text('rent_agreement_url'),
  shopPhotoFrontUrl: text('shop_photo_front_url'),
  shopPhotoInsideUrl: text('shop_photo_inside_url'),
  whatsappNumber: text('whatsapp_number'),
  alternateContact: text('alternate_contact'),
  operatingHours: text('operating_hours'),
  agreedToTerms: boolean('agreed_to_terms'),
  agreedToCompliance: boolean('agreed_to_compliance'),
  agreedToNoBannedDrugs: boolean('agreed_to_no_banned_drugs'),
  selfDeclarationValidLicenses: boolean('self_declaration_valid_licenses'),
  dob: timestamp('dob'),
  gender: text('gender'),
  aadhaarBackUrl: text('aadhaar_back_url'),
  vehicleType: text('vehicle_type'),
  vehicleRegNumber: text('vehicle_reg_number'),
  dlNumber: text('dl_number'),
  dlExpiryDate: timestamp('dl_expiry_date'),
  dlFrontUrl: text('dl_front_url'),
  dlBackUrl: text('dl_back_url'),
  rcUrl: text('rc_url'),
  insuranceUrl: text('insurance_url'),
  emergencyContactName: text('emergency_contact_name'),
  emergencyContactNumber: text('emergency_contact_number'),
  upiId: text('upi_id'),
  preferredZones: jsonb('preferred_zones'),
  availableHours: text('available_hours'),
  daysAvailable: text('days_available'),
  employmentType: text('employment_type'),
  noCriminalRecord: boolean('no_criminal_record'),
  policeVerificationUrl: text('police_verification_url'),
  referenceContact: text('reference_contact'),
  agreedToGpsTracking: boolean('agreed_to_gps_tracking'),
  agreedToHandleMeds: boolean('agreed_to_handle_meds'),
  acknowledgeSla: boolean('acknowledge_sla'),
  consentBackgroundCheck: boolean('consent_background_check'),
  mfaSecret: text('mfa_secret'),
  isMfaEnabled: boolean('is_mfa_enabled').default(false),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

export const hospitals = pgTable('hospitals', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  slug: text('slug').unique(),
  address: text('address').notNull(),
  city: text('city').notNull(),
  email: text('email'),
  image: text('image'),
  images: jsonb('images'),
  isOpen24Hours: boolean('is_open_24_hours').default(false).notNull(),
  consultationFee: numeric('consultation_fee').notNull(),
  governmentSchemes: jsonb('government_schemes'),
  isOnlinePaymentAvailable: boolean('is_online_payment_available').default(true).notNull(),
  ambulanceContact: text('ambulance_contact'),
  contactNumber: text('contact_number'),
  phoneNumbers: jsonb('phone_numbers'),
  description: text('description'),
  rating: numeric('rating').default('0'),
  doctors: jsonb('doctors'),
  managementType: text('management_type').default('SELF'),
  isVerified: boolean('is_verified').default(false),
  plan: text('plan').default('Standard'),
  isFeatured: boolean('is_featured').default(false),
  hasGovtSchemes: boolean('has_govt_schemes').default(false),
  hasCustomPage: boolean('has_custom_page').default(false),
  isSpotlight: boolean('is_spotlight').default(false),
  prioritySupport: boolean('priority_support').default(false),
  userId: text('user_id').references(() => users.id, { onDelete: 'set null' }),
  tempPassword: text('temp_password'),
  hospitalType: text('hospital_type').default('Private'),
  bedCapacity: integer('bed_capacity').default(50),
  specialities: jsonb('specialities'),
  trialEndDate: timestamp('trial_end_date'),
  bankDetails: jsonb('bank_details'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

export const doctors = pgTable('doctors', {
  id: text('id').primaryKey(),
  hospitalId: text('hospital_id').notNull().references(() => hospitals.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  email: text('email'),
  phone: text('phone'),
  specialty: text('specialty').notNull(),
  fee: numeric('fee').notNull(),
  availability: jsonb('availability'),
  isActive: boolean('is_active').default(true).notNull(),
  isSpecialtyGroup: boolean('is_specialty_group').default(false),
  department: text('department'),
  maxAppointmentsPerSlot: integer('max_appointments_per_slot').default(1),
  doctorsCount: integer('doctors_count').default(1),
  description: text('description'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

export const slots = pgTable('slots', {
  id: text('id').primaryKey(),
  doctorId: text('doctor_id').notNull().references(() => doctors.id, { onDelete: 'cascade' }),
  hospitalId: text('hospital_id').notNull().references(() => hospitals.id, { onDelete: 'cascade' }),
  startTime: timestamp('start_time').notNull(),
  endTime: timestamp('end_time').notNull(),
  status: text('status').default('available').notNull(),
  appointmentId: text('appointment_id'),
  cancelledAt: timestamp('cancelled_at'),
  cancellationReason: text('cancellation_reason'),
  cancelledBy: text('cancelled_by').references(() => users.id, { onDelete: 'set null' }),
  bookedCount: integer('booked_count').default(0).notNull(),
  maxAppointments: integer('max_appointments').default(1).notNull(),
  holdCount: integer('hold_count').default(0).notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

export const appointments = pgTable('appointments', {
  id: text('id').primaryKey(),
  patientId: text('patient_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  doctorId: text('doctor_id').notNull().references(() => doctors.id, { onDelete: 'cascade' }),
  hospitalId: text('hospital_id').notNull().references(() => hospitals.id, { onDelete: 'cascade' }),
  slotId: text('slot_id').references(() => slots.id, { onDelete: 'set null' }),
  slotTime: timestamp('slot_time').notNull(),
  status: text('status').default('pending').notNull(),
  paymentStatus: text('payment_status').default('unpaid').notNull(),
  paymentSource: text('payment_source').default('manual').notNull(),
  paymentUpdatedAt: timestamp('payment_updated_at'),
  paymentUpdatedBy: text('payment_updated_by').references(() => users.id, { onDelete: 'set null' }),
  bookingDate: timestamp('booking_date').defaultNow().notNull(),
  notes: text('notes'),
  prescriptionUrl: text('prescription_url'),
  prescriptionBase64: text('prescription_base64'),
  prescriptionUploadedAt: timestamp('prescription_uploaded_at'),
  invoiceUrl: text('invoice_url'),
  tokenNumber: integer('token_number'),
  patientName: text('patient_name'),
  patientPhone: text('patient_phone'),
  patientEmail: text('patient_email'),
  patientAge: integer('patient_age'),
  doctorName: text('doctor_name'),
  hospitalName: text('hospital_name'),
  consultationFee: numeric('consultation_fee'),
  appointmentDate: text('appointment_date'),
  appointmentTime: text('appointment_time'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

export const donors = pgTable('donors', {
  id: text('id').primaryKey(),
  userId: text('user_id').references(() => users.id, { onDelete: 'set null' }),
  name: text('name').notNull(),
  email: text('email'),
  bloodGroup: text('blood_group').notNull(),
  gender: text('gender').default('Other'),
  age: integer('age').notNull(),
  phone: text('phone'),
  address: text('address').notNull(),
  area: text('area').notNull(),
  city: text('city').notNull(),
  lastDonationDate: timestamp('last_donation_date'),
  isAvailable: boolean('is_available').default(true).notNull(),
  source: text('source').default('user_panel'),
  location: jsonb('location'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});
